from setuptools import setup

APP = ['menu_bar_app.py']
DATA_FILES = []
OPTIONS = {
    'iconfile': 'bitcoin_tracker_icon.icns',
    'argv_emulation': True,
    'packages': ['requests'],
    'plist': {
        'CFBundleName': 'Bitcoin Menu Bar App',
        'CFBundleDisplayName': 'Bitcoin Menu Bar App',
        'CFBundleGetInfoString': 'Bitcoin Menu Bar App',
        'CFBundleVersion': '1.0.0',
        'CFBundleShortVersionString': '1.0',
        'CFBundleIdentifier': 'com.defendersoftheinternet.bitcoinmenubar',
        'CFBundleDevelopmentRegion': 'en',
        'CFBundleIconFile': 'bitcoin_tracker_icon.icns',  # Add this line
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['menu_bar_app.py']
DATA_FILES = []
OPTIONS = {
    'iconfile': 'bitcoin_tracker_icon.icns',
    'argv_emulation': True,
    'plist': {
        'LSUIElement': True,
    },
    'packages': ['rumps', 'requests'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
